## Working with JSON

In [1]:
import pandas as pd

Reading JSON from local machine

In [2]:
df = pd.read_json('train.json')

In [3]:
df.head(7)

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...
5   6602     jamaican  [plain flour, sugar, butter, eggs, fresh ginge...
6  42779      spanish  [olive oil, salt, medium shrimp, pepper, garli...

Reading JSON from urls

In [4]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,0.0437
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,0.8370
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,1.0700
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,4.6100
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,0.0213
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,1.2800
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,2.9800
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,0.2110
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,0.3140
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-09-08,1725753601,0.1650

## Working with SQL

In [10]:
import mysql.connector
import warnings
warnings.filterwarnings(action='ignore')

In [11]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world')

In [13]:
city_df = pd.read_sql_query('SELECT * FROM city', conn)

In [25]:
pd.read_sql_query("SELECT * FROM country WHERE Population > 6695000", conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
1,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56,AO
2,ARG,Argentina,South America,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rúa,69,AR
3,AUS,Australia,Oceania,Australia and New Zealand,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135,AU
4,AUT,Austria,Europe,Western Europe,83859.0,1918.0,8091800,77.7,211860.0,206025.0,Österreich,Federal Republic,Thomas Klestil,1523,AT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780,YE
90,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792,YU
91,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716,ZA
92,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162,ZM
93,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068,ZW

In [30]:
pd.read_sql_query('SELECT * FROM countrylanguage WHERE Language LIKE "English"', conn)

   CountryCode Language IsOfficial  Percentage
0          ABW  English          F         9.5
1          AIA  English          T         0.0
2          ANT  English          F         7.8
3          ASM  English          T         3.1
4          ATG  English          T         0.0
5          AUS  English          T        81.2
6          BHR  English          F         0.0
7          BLZ  English          T        50.8
8          BMU  English          T       100.0
9          BRB  English          T         0.0
10         BRN  English          F         3.1
11         CAN  English          T        60.4
12         CCK  English          T         0.0
13         COK  English          F         0.0
14         CXR  English          T         0.0
15         CYM  English          T         0.0
16         DNK  English          F         0.3
17         FLK  English          T         0.0
18         GBR  English          T        97.3
19         GIB  English          T        88.9
20         GUM  English          T        37.5
21         HKG  English          T         2.2
22         IRL  English          T        98.4
23         ISL  English          F         0.0
24         JPN  English          F         0.1
25         KNA  English          T         0.0
26         KWT  English          F         0.0
27         LCA  English          T        20.0
28         LSO  English          T         0.0
29         MAC  English          F         0.5
30         MCO  English          F         6.5
31         MDV  English          F         0.0
32         MHL  English          T         0.0
33         MLT  English          T         2.1
34         MNP  English          T         4.8
35         MSR  English          T         0.0
36         MYS  English          F         1.6
37         NFK  English          T         0.0
38         NIU  English          T         0.0
39         NOR  English          F         0.5
40         NRU  English          T         7.5
41         NZL  English          T        87.0
42         PLW  English          T         3.2
43         PRI  English          F        47.4
44         SHN  English          T         0.0
45         SYC  English          T         3.8
46         TCA  English          T         0.0
47         TKL  English          T         0.0
48         TON  English          T         0.0
49         TTO  English          F        93.5
50         TUV  English          T         0.0
51         UMI  English          T         0.0
52         USA  English          T        86.2
53         VCT  English          T         0.0
54         VGB  English          T         0.0
55         VIR  English          T        81.7
56         VUT  English          T        28.3
57         WSM  English          T         0.6
58         ZAF  English          T         8.5
59         ZWE  English          T         2.2