In [96]:
import pandas as pd
import numpy as np

In [97]:
df = pd.read_csv('play_tennis.csv')
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [98]:
df.drop(columns=['day'], axis=1, inplace=True) # removing `day` col
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [99]:
# P(Yes) & P(No)
df.value_counts('play')

play
Yes    9
No     5
Name: count, dtype: int64

In [100]:
p_yes, p_no = 9/14, 5/14
print(f'P(y): {p_yes}\nP(n): {p_no}')

P(y): 0.6428571428571429
P(n): 0.35714285714285715

In [101]:
# for outlook col:
outlook_cross_tab = pd.crosstab(df['outlook'], df['play'])

P_of_no = 0
P_of_rain_no = 2/5
P_of_sunny_no = 3/5

P_of_yes = 4/9
P_of_rain_yes = 3/9
P_of_sunny_yes = 2/9

outlook_cross_tab

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [102]:
# for temp col:
temp_cross_tab = pd.crosstab(df['temp'], df['play'])

P_of_cool_no = 1/5
P_of_hot_no = 2/5
P_of_mild_no = 2/5

P_of_cool_yes = 3/9
P_of_mild_yes = 4/9
P_of_hot_yes = 2/9

temp_cross_tab

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [103]:
# for humidity col:
humidity_cross_tab = pd.crosstab(df['humidity'], df['play'])

P_high_no = 4/5
P_normal_no = 1/5

P_high_yes = 3/9
P_normal_yes = 6/9

humidity_cross_tab

play      No  Yes
humidity
High       4    3
Normal     1    6

In [104]:
# for wind col:
wind_cross_tab = pd.crosstab(df['wind'], df['play'])

P_of_strong_no = 3/5
P_of_weak_no = 2/5

P_of_strong_yes = 3/9
P_of_weak_yes = 6/9

wind_cross_tab

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [105]:
# Question:  outlook=Sunny, temp=Hot, wind=Weak

P_of_yes_of_Q = (p_yes * P_of_sunny  * P_of_hot * P_high_yes * P_of_weak_yes)
P_of_no_of_Q = (p_no * P_of_sunny_no * P_of_hot_no * P_high_no * P_of_weak_no )

print(f'Probablity of Yes: {P_of_yes_of_Q}\nProbablity of No: {P_of_no_of_Q}')

Probablity of Yes: 0.007054673721340388
Probablity of No: 0.02742857142857143

### Conclusion: No Play