In [127]:
import warnings
warnings.filterwarnings(action='ignore')

In [128]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer, MissingIndicator

In [129]:
df = pd.read_csv('titanic_toy.csv')
df.head(5)

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [130]:
X, y = df.iloc[:,:-1], df.iloc[:,-1]

In [131]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [132]:
sim_imputer = SimpleImputer()

In [133]:
X_train_trf = sim_imputer.fit_transform(X_train)
X_test_trf = sim_imputer.transform(X_test)

In [134]:
log_reg = LogisticRegression()

In [135]:
log_reg.fit(X_train_trf, y_train)
y_pred = log_reg.predict(X_test_trf)
print(accuracy_score(y_test, y_pred))

0.6536312849162011

In [136]:
miss_indicator = MissingIndicator(features='all')

In [137]:
missing_cols = miss_indicator.feature_names_in_[miss_indicator.features]

AttributeError: 'MissingIndicator' object has no attribute 'feature_names_in_'

In [139]:
X_train_missing = pd.DataFrame(X_train_missing, columns=[col + '_NA' for col in missing_cols], index=X_train.index)
X_test_missing = pd.DataFrame(X_test_missing, columns=[col + '_NA' for col in missing_cols], index=X_test.index)

X_train = pd.concat([X_train, X_train_missing], axis=1)
X_test = pd.concat([X_test, X_test_missing], axis=1)

In [140]:
X_train

      Age      Fare  Family  Age_NA  Fare_NA  Family_NA
331  45.5   28.5000       0   False    False      False
733  23.0   13.0000       0   False    False      False
382  32.0    7.9250       0   False    False      False
704  26.0    7.8542       1   False    False      False
813   6.0   31.2750       6   False    False      False
..    ...       ...     ...     ...      ...        ...
106  21.0    7.6500       0   False    False      False
270   NaN   31.0000       0    True    False      False
860  41.0       NaN       2   False     True      False
435  14.0  120.0000       3   False    False      False
102  21.0   77.2875       1   False    False      False

[712 rows x 6 columns]

In [141]:
sim_imputer = SimpleImputer()
X_train_missing_trf = sim_imputer.fit_transform(X_train)
X_test_missing_trf = sim_imputer.transform(X_test)

In [142]:
log_reg.fit(X_train_missing_trf, y_train)
y_pred_missing = log_reg.predict(X_test_missing_trf)
print(accuracy_score(y_test, y_pred_missing))

0.6480446927374302

### Without using MissingIndicator class explicitly

In [143]:
si = SimpleImputer(add_indicator=True)
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [144]:
log_reg.fit(X_train_trf, y_train)
y_pred_trf = log_reg.predict(X_test_trf)
print(accuracy_score(y_test, y_pred_trf))

0.6424581005586593