In [91]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [92]:
mnist = fetch_openml('mnist_784', version=1, as_frame=True)

In [93]:
X, y = mnist.data, mnist.target

In [94]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [95]:
log_reg = LogisticRegression(max_iter=1000)
dtree = DecisionTreeClassifier()

In [96]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [97]:
log_reg.fit(X_train_scaled, y_train)
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

In [98]:
ypred_log_reg = log_reg.predict(X_test_scaled)
ypred_dtree = dtree.predict(X_test)

In [99]:
print('For Logistic Regression Model: [Precision, Recall, F1-score, Confusion Matrix]')
# Precision
print('-'*70)
print(f'[Individual Precision]:\n{precision_score(y_test, ypred_log_reg, average=None)}')
print()
print(f'[Macro Precision] - {precision_score(y_test, ypred_log_reg, average='macro')}')
print(f'[Weighted Precision] - {precision_score(y_test, ypred_log_reg, average='weighted')}')

# Recall
print('-'*70)
print(f'[Individual Recall]:\n{recall_score(y_test, ypred_log_reg, average=None)}')
print()
print(f'[Macro Recall] - {recall_score(y_test, ypred_log_reg, average='macro')}')
print(f'[Weighted Recall] - {recall_score(y_test, ypred_log_reg, average='weighted')}')

# F1-score
print('-'*70)
print(f'[Individual F1-score]:\n{f1_score(y_test, ypred_log_reg, average=None)}')
print()
print(f'[Macro F1-score] - {f1_score(y_test, ypred_log_reg, average='macro')}')
print(f'[Weighted F1-score] - {f1_score(y_test, ypred_log_reg, average='weighted')}')

# Classificaion Matrix
print()
print('Calssification Report:')
print(classification_report(y_test, ypred_log_reg))

# Confusion Matrix
print()
print('Confusion Matrix:')
pd.DataFrame(confusion_matrix(y_test, ypred_log_reg))

For Logistic Regression Model: [Precision, Recall, F1-score, Confusion Matrix]
----------------------------------------------------------------------
[Individual Precision]:
[0.95746269 0.94410693 0.89818182 0.90334044 0.92093023 0.87933754
 0.9321075  0.92357936 0.8960739  0.89230769]

[Macro Precision] - 0.9147428094943523
[Weighted Precision] - 0.9153452586653339
----------------------------------------------------------------------
[Individual Recall]:
[0.9553239  0.97125    0.89492754 0.88695045 0.91737452 0.87588374
 0.94412607 0.9407851  0.8577745  0.89859155]

[Macro Recall] - 0.9142987370958867
[Weighted Recall] - 0.9155714285714286
----------------------------------------------------------------------
[Individual F1-score]:
[0.9563921  0.95748614 0.89655172 0.89507042 0.91914894 0.87760724
 0.93807829 0.93210283 0.87650602 0.8954386 ]

[Macro F1-score] - 0.914438230621243
[Weighted F1-score] - 0.9153736378324876

Calssification Report:
              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1343
           1       0.94      0.97      0.96      1600
           2       0.90      0.89      0.90      1380
           3       0.90      0.89      0.90      1433
           4       0.92      0.92      0.92      1295
           5       0.88      0.88      0.88      1273
           6       0.93      0.94      0.94      1396
           7       0.92      0.94      0.93      1503
           8       0.90      0.86      0.88      1357
           9       0.89      0.90      0.90      1420

    accuracy                           0.92     14000
   macro avg       0.91      0.91      0.91     14000
weighted avg       0.92      0.92      0.92     14000


Confusion Matrix:

      0     1     2     3     4     5     6     7     8     9
0  1283     1    11     0     1    13    22     4     6     2
1     0  1554     6     9     3     5     1     4    15     3
2     5    19  1235    18    13    13    21    16    28    12
3     7     9    37  1271     1    40     7    21    21    19
4     6     2    11     4  1188     5    12     9     9    49
5    11    11    10    42    12  1115    20     1    35    16
6     6     5    19     1    16    22  1318     3     6     0
7     4     4    23     4    13     6     0  1414     2    33
8    11    32    16    43     5    44    13     9  1164    20
9     7     9     7    15    38     5     0    50    13  1276

In [100]:
print('For Decison Tree Model: [Precision, Recall, F1-score, Confusion Matrix]')
# Precision
print('-'*70)
print(f'[Individual Precision]:\n{precision_score(y_test, ypred_dtree, average=None)}')
print()
print(f'[Macro Precision] - {precision_score(y_test, ypred_dtree, average='macro')}')
print(f'[Weighted Precision] - {precision_score(y_test, ypred_dtree, average='weighted')}')

# Recall
print('-'*70)
print(f'[Individual Recall]:\n{recall_score(y_test, ypred_dtree, average=None)}')
print()
print(f'[Macro Recall] - {recall_score(y_test, ypred_dtree, average='macro')}')
print(f'[Weighted Recall] - {recall_score(y_test, ypred_dtree, average='weighted')}')

# F1-score
print('-'*70)
print(f'[Individual F1-score]:\n{f1_score(y_test, ypred_dtree, average=None)}')
print()
print(f'[Macro F1-score] - {f1_score(y_test, ypred_dtree, average='macro')}')
print(f'[Weighted F1-score] - {f1_score(y_test, ypred_dtree, average='weighted')}')

# Classificaion Matrix
print()
print('Calssification Report:')
print(classification_report(y_test, ypred_dtree))

# Confusion Matrix
print()
print('Confusion Matrix:')
pd.DataFrame(confusion_matrix(y_test, ypred_dtree))

For Decison Tree Model: [Precision, Recall, F1-score, Confusion Matrix]
----------------------------------------------------------------------
[Individual Precision]:
[0.92216457 0.94168734 0.87082067 0.83646486 0.84092606 0.83241107
 0.90214286 0.90371846 0.8145101  0.82487839]

[Macro Precision] - 0.8689724370354102
[Weighted Precision] - 0.8706078396651067
----------------------------------------------------------------------
[Individual Recall]:
[0.92628444 0.94875    0.83043478 0.83879972 0.86949807 0.82717989
 0.90472779 0.90552229 0.80250553 0.83591549]

[Macro Recall] - 0.8689618003128823
[Weighted Recall] - 0.8706428571428572
----------------------------------------------------------------------
[Individual F1-score]:
[0.92421991 0.94520548 0.85014837 0.83763066 0.85497342 0.82978723
 0.90343348 0.90461947 0.80846325 0.83036027]

[Macro F1-score] - 0.8688841547565544
[Weighted F1-score] - 0.8705448386618329

Calssification Report:
              precision    recall  f1-score   support

           0       0.92      0.93      0.92      1343
           1       0.94      0.95      0.95      1600
           2       0.87      0.83      0.85      1380
           3       0.84      0.84      0.84      1433
           4       0.84      0.87      0.85      1295
           5       0.83      0.83      0.83      1273
           6       0.90      0.90      0.90      1396
           7       0.90      0.91      0.90      1503
           8       0.81      0.80      0.81      1357
           9       0.82      0.84      0.83      1420

    accuracy                           0.87     14000
   macro avg       0.87      0.87      0.87     14000
weighted avg       0.87      0.87      0.87     14000


Confusion Matrix:

      0     1     2     3     4     5     6     7     8     9
0  1244     1    18     4     8    13    22     5    21     7
1     0  1518     4    10    14    10     7    11    21     5
2    15    24  1146    41    26    16    26    25    41    20
3     9     9    35  1202     7    69    12    30    29    31
4    11     4    12    12  1126    11    15    19    20    65
5    25    16    15    63    17  1053    18     4    35    27
6    23     5    11    10    24    25  1263     4    26     5
7     1    15    19    20    17     6     2  1361    18    44
8    12    14    46    49    27    34    26    12  1089    48
9     9     6    10    26    73    28     9    35    37  1187