In [127]:
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score

In [128]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [129]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [131]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [132]:
X = df.drop(columns=['target'])
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [133]:
print(X_train.shape)
print(X_test.shape)

(242, 13)
(61, 13)

In [134]:
rf_clf = RandomForestClassifier()
gb_clf = GradientBoostingClassifier()
lr_clf = LogisticRegression()
svc = SVC()

In [135]:
rf_clf.fit(X_train, y_train)
rf_y_pred = rf_clf.predict(X_test)
print(f'Random Forest Classifier: {accuracy_score(y_test, rf_y_pred)}')

Random Forest Classifier: 0.8688524590163934

In [136]:
lr_clf.fit(X_train, y_train)
lr_y_pred = lr_clf.predict(X_test)
print(f'Logistic Regression: {accuracy_score(y_test, lr_y_pred)}')

Logistic Regression: 0.8852459016393442

In [137]:
gb_clf.fit(X_train, y_train)
gb_y_pred = gb_clf.predict(X_test)
print(f'Gradient Boosting Classifier: {accuracy_score(y_test, gb_y_pred)}')

Gradient Boosting Classifier: 0.7704918032786885

In [138]:
svc.fit(X_train, y_train)
svc_y_pred = svc.predict(X_test)
print(f'Support Vector Classifier: {accuracy_score(y_test, svc_y_pred)}')

Support Vector Classifier: 0.7049180327868853

In [139]:
from sklearn.model_selection import cross_val_score
print('Random Forest:',np.mean(cross_val_score(rf_clf, X, y, cv=10, scoring='accuracy')))
print('Gradient Boosting:',np.mean(cross_val_score(gb_clf, X, y, cv=10, scoring='accuracy')))
print('Support Vector Classifier:',np.mean(cross_val_score(svc, X, y, cv=10, scoring='accuracy')))
print('Logistic Regression:',np.mean(cross_val_score(lr_clf, X, y, cv=10, scoring='accuracy')))

Random Forest: 0.8249462365591398
Gradient Boosting: 0.8013978494623656
Support Vector Classifier: 0.6604301075268817
Logistic Regression: 0.8316129032258065